name: guruwisdom-test
services:
  app:
    container_name: guruwisdom-test
    image: ghcr.io/markuswolffaix/guru-wisdom.de-app:latest
    ports:
      - "80:80"          
    environment:
      - SERVER_NAME=:80
      - APP_ENV=test
    restart: unless-stopped
    tty: true
    volumes:
      - app_runtime:/app/runtime
      - caddy_data:/data
      - caddy_config:/config

volumes:
  app_runtime:
  caddy_data:
  caddy_config: