name: guruwisdom-dev
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev       
    ports:
      - "8080:80"        
    environment:
      - SERVER_NAME=:80
      - APP_ENV=dev
      - XDEBUG_MODE=debug
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config

volumes:
  app_public_assets:
  app_runtime:
  caddy_data:
  caddy_config: