services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev # Wichtig: Sagt Docker, dass wir die "dev" Stage aus dem Dockerfile wollen
    ports:
      - "8080:80" # Erreichbar im Browser unter http://localhost:8080
    volumes:
      - ./:/app
    environment:
      - SERVER_NAME=:80 # Sagt FrankenPHP, dass es auf Port 80 ohne SSL lauschen soll
      - APP_ENV=dev
      # FrankenPHP sucht automatisch nach einem "public" Ordner als Einstiegspunkt, 
      # was perfekt für Yii3 ist!
    tty: true
